### PR TITLE
Add server deployment steps for Nathan

### PR DESCRIPTION
**Pull request by austinjpaul**
instructions in Readme.md, supervisor.conf file also.

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Could we make a `docs/` and `devops/` directory to mimic the structure of https://github.com/transitmatters/new-train-tracker - README and LICENSE can go in the former and supervisor conf file (and the ansible playbook I'll add later) in the latter

**Comment by nathan-weinberg** [comment]
Content looks good - we might want to cleanup and formalize the whole README at some point closer to release

**Comment by austinjpaul** [comment]
Someone else should add the license.
Sorry for dropping the ball here. Is it good to go?

**Comment by MattWis** [comment]
I opened a PR to add an MIT license: https://github.com/transitmatters/regional-rail-explorer/pull/24

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
